apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: products
    spec:
      securityContext:
        runAsUser: 1000300
      containers:
        - name: products
          image: codeurjc/products
          imagePullPolicy: IfNotPresent
          env:
            - name: NOTIFICATIONS_URL
              value: http://notifications:8070
            - name: USE_NOTIFICATION_SERVICE
              value: "true"
            - name: SPRING_ZIPKIN_BASEURL
              value: "http://zipkin:9411"
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
spec:
  ports:
    - port: 8060
  selector:
    app: products
  type: ClusterIP
