version: '3.9'

services:

  1-strangler-fig-monolith_quarkus:
    image: 1_strangler_fig_monolith_quarkus
    container_name: '1_strangler_fig_monolith_quarkus'
    restart: on-failure
    build: 
      context: ./1_strangler_fig_monolith_quarkus
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports: 
      - 8080:8080
    networks:
      - app-network
    environment:
      - PAYROLL_TOPIC=payroll-v1-topic
      - INVOICING_TOPIC=invoicing-v1-topic
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CONSUMER_GROUP_ID=payment-service-group

networks:
  app-network:
    driver: bridge