apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orders
    spec:
      securityContext:
        runAsUser: 1000300
      containers:
        - env:
            - name: MONOLITH_URL
              value: http://monolith:8080
            - name: SPRING_ZIPKIN_BASEURL
              value: "http://zipkin:9411"
          image: codeurjc/orders
          name: orders
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders
  name: orders
spec:
  ports:
    - port: 8090
  selector:
    app: orders
  type: ClusterIP
