version: '3.9'
services: 
  1-strangler-fig-monolith_quarkus:
    image: 1-strangler-fig-monolith_quarkus
    container_name: '1-strangler-fig-monolith_quarkus'
    restart: on-failure
    build: 
      context: ./1_strangler_fig_monolith
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports: 
      - "8080:8080"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge