version: '3.9'
services:
  2-strangler-fig-inventory-ms_quarkus:
    image: 2-strangler-fig-inventory-ms_quarkus
    container_name: '2-strangler-fig-inventory-ms_quarkus'
    restart: on-failure
    build:
      context: ./2_strangler_fig_inventory_ms
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports: 
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge